let express = require('express')
let app = express()
app.use(require('cors')())
app.use(express.json())
let api = require('./controller')
app.get('/api/houses', api.getHouses)
app.delete('/api/houses/:id', api.deleteHouse)
app.post('/api/houses', api.createHouse)
app.put('/api/houses/:id', api.updateHouse)
app.listen(4004)